## AND

In [41]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.13389
iteration=  1000 cost=  0.485
iteration=  2000 cost=  0.371346
iteration=  3000 cost=  0.305129
iteration=  4000 cost=  0.261117
iteration=  5000 cost=  0.229163
iteration=  6000 cost=  0.204584
iteration=  7000 cost=  0.184928
iteration=  8000 cost=  0.168772
iteration=  9000 cost=  0.155217
iteration=  10000 cost=  0.143661
iteration=  11000 cost=  0.133683
iteration=  12000 cost=  0.124975
Validating output for AND GATE
[[ 0.00543656]
 [ 0.13204534]
 [ 0.13374065]
 [ 0.81120849]]


## OR

In [21]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.425902
iteration=  1000 cost=  0.273831
iteration=  2000 cost=  0.221601
iteration=  3000 cost=  0.185532
iteration=  4000 cost=  0.159031
iteration=  5000 cost=  0.138802
iteration=  6000 cost=  0.122897
iteration=  7000 cost=  0.110092
iteration=  8000 cost=  0.0995812
iteration=  9000 cost=  0.0908126
iteration=  10000 cost=  0.0833964
iteration=  11000 cost=  0.0770495
iteration=  12000 cost=  0.0715613
Validating output for OR GATE
[[ 0.15094057]
 [ 0.94024235]
 [ 0.94150138]
 [ 0.99929845]]


## AND

In [25]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,1])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([1,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=[[0],[1]]
op=[[1],[0]]
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for NOT GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.690432
iteration=  1000 cost=  0.372526
iteration=  2000 cost=  0.240415
iteration=  3000 cost=  0.172935
iteration=  4000 cost=  0.133452
iteration=  5000 cost=  0.107985
iteration=  6000 cost=  0.0903613
iteration=  7000 cost=  0.0775135
iteration=  8000 cost=  0.0677666
iteration=  9000 cost=  0.060137
iteration=  10000 cost=  0.0540129
iteration=  11000 cost=  0.0489948
iteration=  12000 cost=  0.0448118
Validating output for AND GATE
[[ 0.94738775]
 [ 0.03494395]]


## X-OR

In [37]:
import tensorflow as tf
import numpy as np
0
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights_1 = tf.Variable(tf.random_uniform([2,2], -1, 1), name="weights_1")
weights_2 = tf.Variable(tf.random_uniform([2,1], -1, 1), name="weights_2")


Bias1 = tf.Variable(tf.zeros([2]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1]), name="Bias2")

multiply1 = tf.sigmoid(tf.matmul(x, weights_1) + Bias1) 
z = tf.sigmoid(tf.matmul(multiply1, weights_2) + Bias2)

cost = tf.reduce_mean(( (y * tf.log(z)) + ((1 - y) * tf.log(1.0 - z)) ) * -1)

optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[0]])


init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(80000):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            sess.run(weights_1)
            sess.run(Bias1)
            sess.run(weights_2)
            sess.run(Bias2)
            result=sess.run(z,feed_dict={x:inp})
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for XOR GATE")
    print (result)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
iteration=  0 cost=  0.697228
iteration=  1000 cost=  0.69253
iteration=  2000 cost=  0.691947
iteration=  3000 cost=  0.691348
iteration=  4000 cost=  0.690695
iteration=  5000 cost=  0.689949
iteration=  6000 cost=  0.689066
iteration=  7000 cost=  0.687987
iteration=  8000 cost=  0.686638
iteration=  9000 cost=  0.684916
iteration=  10000 cost=  0.682676
iteration=  11000 cost=  0.679718
iteration=  12000 cost=  0.675758
iteration=  13000 cost=  0.670397
iteration=  14000 cost=  0.663072
iteration=  15000 cost=  0.65301
iteration=  16000 cost=  0.639185
iteration=  17000 cost=  0.620323
iteration=  18000 cost=  0.595046
iteration=  19000 cost=  0.562257
iteration=  20000 cost=  0.521769
iteration=  21000 cost=  0.474917
iteration=  22000 cost=  0.42458
iteration=  23000 cost=  0.374341
iteration=  24000 cost=  0.3273
iteration=  25000 cost=  0.285347
iteration=  26000 cost=  0.249139
iteration=  27000 cost=  0

## X-NOR

In [36]:
import tensorflow as tf
import numpy as np
0
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights_1 = tf.Variable(tf.random_uniform([2,2], -1, 1), name="weights_1")
weights_2 = tf.Variable(tf.random_uniform([2,1], -1, 1), name="weights_2")


Bias1 = tf.Variable(tf.zeros([2]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1]), name="Bias2")

multiply1 = tf.sigmoid(tf.matmul(x, weights_1) + Bias1) 
z = tf.sigmoid(tf.matmul(multiply1, weights_2) + Bias2)

cost = tf.reduce_mean(( (y * tf.log(z)) + ((1 - y) * tf.log(1.0 - z)) ) * -1)

optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[0],[0],[1]])


init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(60000):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            sess.run(weights_1)
            sess.run(Bias1)
            sess.run(weights_2)
            sess.run(Bias2)
            result=sess.run(z,feed_dict={x:inp})
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for X-NOR GATE")
    print (result)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
iteration=  0 cost=  0.726782
iteration=  1000 cost=  0.693049
iteration=  2000 cost=  0.693015
iteration=  3000 cost=  0.693003
iteration=  4000 cost=  0.692989
iteration=  5000 cost=  0.692975
iteration=  6000 cost=  0.692959
iteration=  7000 cost=  0.692942
iteration=  8000 cost=  0.692923
iteration=  9000 cost=  0.692902
iteration=  10000 cost=  0.692879
iteration=  11000 cost=  0.692853
iteration=  12000 cost=  0.692824
iteration=  13000 cost=  0.692791
iteration=  14000 cost=  0.692754
iteration=  15000 cost=  0.692713
iteration=  16000 cost=  0.692666
iteration=  17000 cost=  0.692612
iteration=  18000 cost=  0.69255
iteration=  19000 cost=  0.692478
iteration=  20000 cost=  0.692396
iteration=  21000 cost=  0.692299
iteration=  22000 cost=  0.692186
iteration=  23000 cost=  0.692052
iteration=  24000 cost=  0.691892
iteration=  25000 cost=  0.691701
iteration=  26000 cost=  0.69147
iteration=  27000 cost=